@api = http://localhost:3020/api/pwa/ordenes
##GET ALL
GET {{api}}
### POST ITEM PRODUCTO Y/O SERVICIO
POST {{api}}
Content-Type: application/json

{
  "pedido": {
    "id": 1,
    "fecha_pedido": "2023-09-27T10:00:00",
    "cliente": {
      "nombre": "Eduardo Diaz",
      "email": "Eduardo@gmail.com",
      "telefono": "311-246-7900",
      "direccion_envio": {
        "calle": "Calle Platino 116",
        "ciudad": "Ciudad XYZ",
        "codigo_postal": "12345",
        "pais": "País ABC"
      }
    },
    "productos": [
      {
        "id": 101,
        "nombre": "Camiseta",
        "descripcion": "Camiseta de algodón negra",
        "precio_unitario": 190,
        "cantidad": 2,
        "subtotal": 380
      },
      {
        "id": 102,
        "nombre": "Pantalones",
        "descripcion": "Pantalones vaqueros azules",
        "precio_unitario": 40.99,
        "cantidad": 1,
        "subtotal": 40.99
      }
    ],
    "total_subtotal": 420.99,
    "metodo_pago": {
      "tipo": "tarjeta_de_credito",
      "ultimos_cuatro_digitos": "1234",
      "titular": "Eduardo Diaz"
    },
    "estado_pedido": "pendiente",
    "metodo_envio": {
      "tipo": "envio_estandar",
      "fecha_entrega_estimada": "2023-09-30",
      "numero_seguimiento": "123456789"
    },
    "notas_cliente": "Por favor, entregar antes del viernes."
  }
}

##PUT 
PUT {{api}}
Content-Type: 
{
  "_id": {
    "$oid": "6514ca706a217c46653f25e2"
  },
  "pedido": {
    "id": 1,
    "fecha_pedido": "2023-09-27T10:00:00",
    "cliente": {
      "nombre": "Kevin",
      "email": "Eduardo@gmail.com",
      "telefono": "311-246-7900",
      "direccion_envio": {
        "calle": "Calle Platino 116",
        "ciudad": "Ciudad XYZ",
        "codigo_postal": "12345",
        "pais": "País ABC"
      }
    },
    "productos": [
      {
        "id": 101,
        "nombre": "Camiseta",
        "descripcion": "Camiseta de algodón negra",
        "precio_unitario": 190,
        "cantidad": 2,
        "subtotal": 380
      },
      {
        "id": 102,
        "nombre": "Pantalones",
        "descripcion": "Pantalones vaqueros azules",
        "precio_unitario": 40.99,
        "cantidad": 1,
        "subtotal": 40.99
      }
    ],
    "total_subtotal": 420.99,
    "metodo_pago": {
      "tipo": "tarjeta_de_credito",
      "ultimos_cuatro_digitos": "1234",
      "titular": "Eduardo Diaz"
    },
    "estado_pedido": "pendiente",
    "metodo_envio": {
      "tipo": "envio_estandar",
      "fecha_entrega_estimada": "2023-09-30",
      "numero_seguimiento": "123456789"
    },
    "notas_cliente": "Por favor, entregar antes del viernes."
  }
}